// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYXYtJ6znPhsRBUin9eI2BOnONUXaHBvE',
    appId: '1:538001647092:web:1d7a33d4743c382a4e05a1',
    messagingSenderId: '538001647092',
    projectId: 'flutter-ecommerce-app-c3c2e',
    authDomain: 'flutter-ecommerce-app-c3c2e.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app-c3c2e.firebasestorage.app',
    measurementId: 'G-H9HRFRJTHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmUQvppytLA3PibXiwoDeXZOSDAxWnYUM',
    appId: '1:538001647092:android:728913091ee2cd384e05a1',
    messagingSenderId: '538001647092',
    projectId: 'flutter-ecommerce-app-c3c2e',
    storageBucket: 'flutter-ecommerce-app-c3c2e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuZcBC4v3HFpkzR8tJ84nYPuiuizdRjcM',
    appId: '1:538001647092:ios:93bf02ec7b23069a4e05a1',
    messagingSenderId: '538001647092',
    projectId: 'flutter-ecommerce-app-c3c2e',
    storageBucket: 'flutter-ecommerce-app-c3c2e.firebasestorage.app',
    androidClientId: '538001647092-1uujkd6916c3p66hnmad0n2s1igruqpc.apps.googleusercontent.com',
    iosClientId: '538001647092-mok55mn6gffr2t2uebea0fe6paud94md.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuZcBC4v3HFpkzR8tJ84nYPuiuizdRjcM',
    appId: '1:538001647092:ios:93bf02ec7b23069a4e05a1',
    messagingSenderId: '538001647092',
    projectId: 'flutter-ecommerce-app-c3c2e',
    storageBucket: 'flutter-ecommerce-app-c3c2e.firebasestorage.app',
    androidClientId: '538001647092-1uujkd6916c3p66hnmad0n2s1igruqpc.apps.googleusercontent.com',
    iosClientId: '538001647092-mok55mn6gffr2t2uebea0fe6paud94md.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYXYtJ6znPhsRBUin9eI2BOnONUXaHBvE',
    appId: '1:538001647092:web:2dde4ea3e9ea16dc4e05a1',
    messagingSenderId: '538001647092',
    projectId: 'flutter-ecommerce-app-c3c2e',
    authDomain: 'flutter-ecommerce-app-c3c2e.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app-c3c2e.firebasestorage.app',
    measurementId: 'G-N84SSYRJFR',
  );
}
